media: media
content:
  - name: nyheder
    label: Nyheder
    type: collection
    path: _nyheder
    view:
      fields: [ title, date  ]
    fields:
      - { name: layout, type: string, hidden: true, default: nyhed }
      - { name: draft, label: Draft, type: boolean, default: true }
      - { name: cover, label: Cover image, type: image }
      - { name: date, label: Date, type: date, required: true, options: { format: yyyy-MM-dd } }
      - { name: title, label: Title, type: string, required: true }
      - { name: author, label: Authors, type: string, list: true }
      - { name: body, label: Body, type: rich-text }
  - name: aktiviteter
    label: Aktiviteter
    type: collection
    path: _aktiviteter
    view:
      fields: [ title, begin_date, begin_hour, begin_minute, end_date, end_hour, end_minute  ]
    fields:
      - { name: layout, type: string, hidden: true, default: aktivitet }
      - { name: draft, label: Draft, type: boolean, default: true }
      - { name: cover, label: Cover image, type: image }
      - { name: begin_date, label: Start date, type: date, required: true, options: { format: yyyy-MM-dd } }
      - { name: begin_hour, label: Begin hour, type: number, required: false, options: {min: 0, max:23} }
      - { name: begin_minute, label: Begin minute, type: number, required: false, options: {min: 0, max:59} }
      - { name: end_date, label: End date, type: date, required: true, options: { format: yyyy-MM-dd } }
      - { name: end_hour, label: End hour, type: number, required: false, options: {min: 0, max:23} }
      - { name: end_minute, label: End minute, type: number, required: false, options: {min: 0, max:59} }
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
  - name: pages
    label: Pages
    type: collection
    path: _pages
    view:
      fields: [ cover, title ]
    fields:
      - { name: layout, type: string, hidden: true, default: post }
      - { name: cover, label: Cover image, type: image }
      - { name: title, label: Title, type: string, required: true }
      - { name: title_multiline, label: Title Multiline, type: rich-text, required: false}
      - { name: body, label: Body, type: rich-text }